# Generated by Django 4.2.4 on 2023-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bold_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='underlined_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
