# Generated by Django 4.2.4 on 2023-09-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_bold_text_post_subtitles_post_underlined_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bold_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitles',
        ),
        migrations.RemoveField(
            model_name='post',
            name='underlined_text',
        ),
    ]
